### ISSUE TITLE
Need upgrade for hexo 3.0

### ISSUE THREAD

**Issue by fishg** [akfish/hexo-migrator-image#2]
Can't run in hexo 3.0. Need upgrade. Thanks!

**Comment by akfish** [comment]
Noted. 
Hexo 3.0 introduced multiple breaking changes. I'll look into it when I'm free. Hopefully soon.

**Comment by akfish** [comment]
Fixed in 1.0.5
Close #2

**Comment by fishg** [comment]
Great!Thanks！
